import{a as g,S as b,i as c}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();const v="52586947-52be226ea0996a0c8fac5fdee",L="https://pixabay.com/api/";async function q(o,t=1){try{return(await g.get(L,{params:{key:v,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}})).data}catch(n){return console.error("AxiosError:",n),{hits:[],totalHits:0}}}const f=document.querySelector(".gallery"),y=document.getElementById("loader");let S=new b(".gallery a",{captionsData:"alt",captionDelay:250});function w(o){const t=o.map(({webformatURL:n,largeImageURL:s,tags:e,likes:r,views:a,comments:m,downloads:h})=>`
        <li class="gallery-item">
          <div class='gallery-img'>
            <a href="${s}">
              <img src="${n}" alt="${e}" loading="lazy" />
            </a>
          </div>
          <div class="info">
            <div class="info-text"><p><b>Likes:</b> <span class="info-count">${r}</span></p></div>
            <div class="info-text"><p><b>Views:</b> <span class="info-count">${a}</span></p></div>
            <div class="info-text"><p><b>Comments:</b> <span class="info-count">${m}</span></p></div>
            <div class="info-text"><p><b>Downloads:</b> <span class="info-count">${h}</span></p></div>
          </div>
        </li>
      `).join("");f.insertAdjacentHTML("beforeend",t),S.refresh()}function E(){f.innerHTML=""}function x(){y.style.display="block"}function B(){y.style.display="none"}function I(){const o=document.querySelector("#load-more-btn");o.style.display="block"}function d(){const o=document.querySelector("#load-more-btn");o.style.display="none"}const P=document.querySelector("#search-form"),$=document.querySelector("#search-input"),A=document.querySelector("#load-more-btn");let l="",i=1,u=0;async function p(o,t){x();try{const n=await q(o,t);if(!n.hits.length){c.warning({title:"Attention",message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}if(w(n.hits),u=n.totalHits,i*15<u?I():(d(),c.info({title:"Information",message:"We're sorry, but you've reached the end of search results."})),t>1){const e=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(n){console.error(n),c.error({title:"Error",message:"Failed to load data"})}finally{B()}}P.addEventListener("submit",o=>{o.preventDefault();const t=$.value.trim();if(!t){c.error({title:"Error",message:"Enter your search query"});return}t!==l&&(l=t,i=1,u=0,E(),d()),p(l,i)});A.addEventListener("click",()=>{i+=1,p(l,i)});
//# sourceMappingURL=index.js.map
