import{a as b,S as v,i as l}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function s(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const L="52586947-52be226ea0996a0c8fac5fdee",q="https://pixabay.com/api/";function S(r,t=1){return b.get(q,{params:{key:L,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}}).then(o=>o.data).catch(o=>(console.error("AxiosError:",o),{hits:[],totalHits:0}))}const y=document.querySelector(".gallery"),m=document.getElementById("loader");let E=new v(".gallery a",{captionsData:"alt",captionDelay:250});function w(r){const t=r.map(({webformatURL:o,largeImageURL:s,tags:e,likes:n,views:a,comments:h,downloads:g})=>`
      <li class="gallery-item">
      <div class='gallery-img'>
          <a href="${s}">
            <img src="${o}" alt="${e}" loading="lazy" />
          </a>
      </div>
        <div class="info">
          <div class="info-text"><p><b>Likes:</b> <span class="info-count">${n}</ы></span></div>
          <div class="info-text"><p ><b>Views:</b> <span class="info-count">${a}</ы></span></div>
          <div class="info-text"><p><b>Comments:</b> <span class="info-count">${h}</ы></span></div>
          <div class="info-text"><p><b>Downloads:</b> <span class="info-count">${g}</ы></span></div>
        </div>
      </li>
    `).join("");y.insertAdjacentHTML("beforeend",t),E.refresh()}const x=document.querySelectorAll(".gallery li");x.forEach((r,t)=>{t>=9&&(r.style.display="none")});function B(){y.innerHTML=""}function I(){m.style.display="block"}function f(){m.style.display="none"}function A(){const r=document.querySelector("#load-more-btn");r.style.display="block"}function d(){const r=document.querySelector("#load-more-btn");r.style.display="none"}const P=document.querySelector("#search-form"),$=document.querySelector("#search-input"),H=document.querySelector("#load-more-btn");let c="",i=1,u=0;async function p(r,t){I();try{const o=await S(r,t);if(f(),!o.hits.length){l.warning({title:"Attention",message:"Sorry, there are no images matching your search query. Please try again!"}),d();return}if(w(o.hits),u=o.totalHits,i*15<u?A():(d(),l.info({title:"Information",message:"We're sorry, but you've reached the end of search results."})),t>1){const e=document.querySelector(".gallery").firstElementChild.getBoundingClientRect().height;window.scrollBy({top:e*2,behavior:"smooth"})}}catch(o){f(),console.error(o),l.error({title:"Error",message:"Failed to load data"})}}P.addEventListener("submit",r=>{r.preventDefault();const t=$.value.trim();if(!t){l.error({title:"Error",message:"Enter your search query"});return}t!==c&&(c=t,i=1,u=0,B(),d()),p(c,i)});H.addEventListener("click",()=>{i+=1,p(c,i)});
//# sourceMappingURL=index.js.map
